language: rust
sudo: required

matrix:
  include:
    - rust: stable

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - wget
      - clang-3.6
      - cmake
      - python
      - python-virtualenv
      
script:
  - cargo build
  - cargo test
  
  - tmp=$(mktemp -d)
  - pushd "$tmp"
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar zxf master.tar.gz
  - mkdir kcov-master/build
  - cd kcov-master/build
  - cmake ..
  - make
  - make install DESTDIR="$tmp"
  - popd
  
  - mkdir ./target/cov
  - PATH="$tmp/usr/local/bin:$PATH" kcov --verify\
    --coveralls-id=$TRAVIS_JOB_ID \
    --include-pattern '/src' ./target/cov ./target/debug/test_ci
